import { ArrowLeft, ChartArea, MessageSquare, Sparkles } from "lucide-react";
import React from "react";
import { BrowserRouter as Router, Routes, Route, Link, useLocation } from "react-router-dom";
import {cx} from 'class-variance-authority'

const Home = () => (
  <div className="p-6 max-w-3xl mx-auto">
   <img className="max-w-40 mx-auto mb-8" src="/logo.png" />
    <h1 className="text-3xl font-bold mb-4">Turn Conversations into Testimonials — Instantly.</h1>
    <p className="text-lg">
      Our Gmail plugin uses AI to transform your client communications into authentic, compelling testimonials. Simply select an email thread with a client, and our plugin will analyze the exchange to generate a testimonial draft. With a single click, you can edit, approve, and send the testimonial to your client for feedback or approval.
    </p>
    <p className="mt-4 text-sm italic text-gray-500">
      Disclaimer: The testimonial content generated by AI is for informational and creative support only and may require user editing for accuracy, tone, or legal appropriateness.
    </p>
  </div>
);

const PrivacyPolicy = () => (
<div className="px-4 py-10 max-w-3xl mx-auto">
    <h2 className="text-2xl font-bold mb-4">Privacy Policy</h2>
    <p className="mb-2">Effective Date: April 22, 2025</p>
    <p className="mb-4">This Privacy Policy outlines how our Gmail add-on ("we," "our," or "us") collects, uses, and protects your information when using our service.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">1. Data Collection</h3>
    <p>We only access email threads you explicitly select. No other emails or data are accessed or collected.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">2. Data Usage</h3>
    <p>Selected email content is temporarily processed to generate testimonial drafts using the OpenAI API. We do not retain or store email data after processing.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">3. Third-Party Services</h3>
    <p>We utilize OpenAI's API to process content. By using our service, you also agree to OpenAI's data practices as described in their <a href="https://openai.com/privacy" target="_blank" className="text-blue-500 underline">Privacy Policy</a>.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">4. Data Retention</h3>
    <p>No user data is stored or logged. All processing is conducted in-memory and data is discarded immediately afterward.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">5. Data Security</h3>
    <p>We implement reasonable technical measures to safeguard your data during processing. However, no system is entirely secure, and usage is at your own risk.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">6. User Rights</h3>
    <p>You can revoke the plugin's access to your Gmail account anytime via your Google Account settings.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">7. Changes to Policy</h3>
    <p>We may update this policy from time to time. Material changes will be posted on this page with an updated effective date.</p>
  </div>
);

const TermsOfService = () => (
    <div className="px-4 py-10 max-w-3xl mx-auto">
    <h2 className="text-2xl font-bold mb-4">Terms of Service</h2>
    <p className="mb-2">Effective Date: April 22, 2025</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">1. Acceptance of Terms</h3>
    <p>By using our Gmail add-on, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">2. Description of Service</h3>
    <p>The plugin analyzes selected Gmail conversations and uses AI to generate testimonial drafts based on the email content.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">3. User Responsibilities</h3>
    <ul className="list-disc pl-6 space-y-2">
      <li>Ensure you have client permission before using their communication for testimonial generation.</li>
      <li>Review all generated content for accuracy and appropriateness before sharing.</li>
      <li>Do not use the service for illegal, unethical, or abusive purposes.</li>
    </ul>
    <h3 className="text-xl font-semibold mt-4 mb-2">4. AI Disclaimer</h3>
    <p>Generated content may include inaccuracies or biases. Always verify and edit AI-generated text before using it.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">5. Intellectual Property</h3>
    <p>You retain ownership of testimonial drafts generated through your usage. The underlying software and services remain the intellectual property of the developers.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">6. Limitations of Liability</h3>
    <p>We are not liable for any direct, indirect, incidental, or consequential damages resulting from the use or misuse of this plugin.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">7. Termination</h3>
    <p>We reserve the right to terminate or suspend access to the service at our discretion, with or without notice.</p>
    <h3 className="text-xl font-semibold mt-4 mb-2">8. Modifications</h3>
    <p>These terms may be updated from time to time. Continued use of the plugin constitutes acceptance of the new terms.</p>
  </div>
);

const App = () => {

    return(
  <Router>
    <div className="bg-gray-800 font-nunito-sans min-h-screen text-gray-100 flex items-center justify-between flex-col relative">
      <BackButton className="xl:absolute self-start xl:p-0 p-4 top-10 left-10" />
      <div className="grow flex items-center flex-col justify-center">
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/privacy" element={<PrivacyPolicy />} />
        <Route path="/terms" element={<TermsOfService />} />
      </Routes>
      </div>
      <footer className="p-4"> 
        <ul className="flex space-x-4 justify-center text-xs text-gray-400 tracking-wide uppercase">
          <li><Link to="/privacy">Privacy Policy</Link></li>
          <li><Link to="/terms">Terms of Service</Link></li>
        </ul> 
      </footer>
    </div>
  </Router>
)}

const BackButton = ({className}:{className?:string}) => {
    const {pathname} = useLocation()
    
    if (pathname === '/') return null

    return <Link className={cx("flex items-center gap-3", className)} to='/'><ArrowLeft className="size-4" />Back</Link>
}

export { App}
